Centered on asteroid
Celestial-Watch/StarShooter pull request #2
Opened 2024-02-26 14:28 UTC by RobinJehn

2024-03-08 18:08 UTC, RobinJehn commented
@Tait-A Please do a quick review and merge. I wouldn't worry to much about the state of train.py as mark got a rework of that coming on another branch anyhow.

2024-03-08 21:33 UTC, Tait-A commented on src/centered-on-asteroid/model_def.py
> +            n_channels_2 * (image_shape[0] // 2 // 2) * (image_shape[1] // 2 // 2)
this can be // 4

2024-03-08 21:39 UTC, Tait-A commented on src/centered-on-asteroid/visualize.py
> +df = get_dataframe("/Users/robinjehn/Documents/repos/StarShooter/data/csv/")
Extract links to config for generalisation

2024-03-08 21:40 UTC, Tait-A submitted a review, later dismissed
2 comments, in model_def.py and visualise.py

2024-03-09 09:25 UTC, RobinJehn commented on src/centered-on-asteroid/model_def.py
> +            n_channels_2 * (image_shape[0] // 2 // 2) * (image_shape[1] // 2 // 2)
Wasn't super sure, because of rounding. But yeah I think you are right that // 2 // 2 = // 4, but its not always true that // x // y = // xy

2024-03-09 09:35 UTC, RobinJehn commented
Should have addressed the comments, have a quick look over my comments and then merge.

2024-03-09 20:03 UTC, mark-a-austin requested changes

2024-03-09 20:03 UTC, mark-a-austin commented on src/centered-on-asteroid/train.py
> +    best_val_loss = 1_000_000.0
should be torch.inf

2024-03-09 20:03 UTC, mark-a-austin commented on src/centered-on-asteroid/train.py
> +        loss = criterion(preds, labels.float())
Should labels not already be floats? Or add it to the preprocessing of the loader at least

2024-03-09 20:03 UTC, mark-a-austin commented on src/centered-on-asteroid/utils.py
> +        train_data_set, batch_size=batch_size, shuffle=True
perhaps set the drop_last flag on to ensure batch size consistency

2024-03-09 20:03 UTC, mark-a-austin commented on src/centered-on-asteroid/visualize.py
> +model_path = "/Users/robinjehn/Documents/repos/StarShooter/src/centered-on-asteroid/model/end-to-end_20240216_161358/model_20240216_161358_4"
Model path should come from config folder

2024-03-10 17:55 UTC, Tait-A approved these changes, later dismissed

2024-03-11 14:18 UTC, mark-a-austin approved these changes

2024-03-11 14:18 UTC, merged